- name: Backup .zshrc and link to dotdotdot settings
  include_tasks:
    file: "{{ dotdotdot_path }}/ansible/roles/common/tasks/backup_and_create_link.yml"
  loop:
    - { settings_path: "{{ dotdotdot_path }}/system/.zshrc", original_path: "~/.zshrc" }

# git clone https://github.com/robbyrussell/oh-my-zsh.git $DOTDOTDOT_PATH/plugins/oh-my-zsh
- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ dotdotdot_path }}/plugins/oh-my-zsh"
    clone: yes
    update: yes

# git clone https://github.com/zsh-users/zsh-autosuggestions $DOTDOTDOT_PATH/plugins/oh-my-zsh/custom/plugins/zsh-autosuggestions
- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ dotdotdot_path }}/plugins/oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

# git clone https://github.com/zsh-users/zsh-syntax-highlighting $DOTDOTDOT_PATH/plugins/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ dotdotdot_path }}/plugins/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

# chsh -s $(which zsh)
- name: Change default shell to zsh
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

