# https://github.com/gantsign/ansible-role-visual-studio-code/blob/master/tasks/install-apt.yml
- name: install dependencies (apt)
  become: yes
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: install key (apt)
  become: yes
  apt_key:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] {{ visual_studio_code_mirror }}/repos/vscode stable main'
    filename: vscode
    state: present

- name: install VS Code (apt)
  become: yes
  apt:
    name: "code{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: present
