- name: install packages
  become: true
  apt:
    name: 
      - imagemagick
      - ffmpeg
      - flatpak
    state: present
    update_cache: yes

- include_role:
    name: gantsign.golang
  vars:
    golang_version: '{{ dotdotdot_golang_version }}'
    golang_install_dir: "{{ dotdotdot_golang_install_dir }}"

- include_tasks:
    file: install_youtube_dl.yml

- include_tasks:
    file: install_flatpak_packages.yml

- include_tasks:
    file: install_vscode.yml

- include_tasks:
    file: install_glow.yml

- include_tasks:
    file: setup_vscode.yml
