- name: Backup VS Code settings and link to dotdotdot settings
  include_tasks:
    file: "{{ dotdotdot_path }}/ansible/roles/common/tasks/backup_and_create_link.yml"
  loop:
    - { settings_path: "{{ dotdotdot_path }}/system/vscode/settings.json", original_path: "~/.config/Code/User/settings.json" }
    - { settings_path: "{{ dotdotdot_path }}/system/vscode/keybindings.json", original_path: "~/.config/Code/User/keybindings.json" }
    - { settings_path: "{{ dotdotdot_path }}/vscode/snippets", original_path: "~/.config/Code/User/snippets" }
