alias yt="youtube-dl --add-metadata -i"
alias git-url="git config --get remote.origin.url"
alias public-ip="curl ifconfig.co"
alias public-ip-json="curl ifconfig.co/json"
alias ppython="time python -m cProfile -o /tmp/pyprofile"
alias clear-history="cat /dev/null > ~/.bash_history && history -c && exit"
