alias yt="youtube-dl --add-metadata -i"
alias git-url="git config --get remote.origin.url"
alias public-ip="curl ifconfig.co"
alias public-ip-json="curl ifconfig.co/json"
alias ppython="time python -m cProfile -o /tmp/pyprofile"
alias clear-history="cat /dev/null > ~/.bash_history && history -c && exit"
alias jupyter-clear="jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace"
alias jupyter-clear-all="find . -name \"*.ipynb\" | grep -v .ipynb_checkpoints | xargs -I {} jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace {}"
alias sshj="ssh -L 8888:localhost:8888"
